saicaca/fuwari

astro.config.mjs
=> Support remark-math rehype-katex katex

src/content/posts/guide/index.md
=> docs: update example posts

package.json, pnpm-lock.yaml, src/layouts/Layout.astro, src/pages/rss.xml.ts
almost work
- iframe video
FYI: https://docs.astro.build/en/guides/rss/
=> feat: add RSS xml

astro.config.mjs, package.json, pnpm-lock.yaml, src/pages/robots.txt.ts
add `sitemap-index.xml` and add dynamic robots.txt for sitemap.
FYI: [@astrojs/sitemap | Docs](https://docs.astro.build/en/guides/integrations-guide/sitemap/#changefreq-lastmod-and-priority)
=> feat: add sitemap

src/layouts/Layout.astro, src/layouts/MainGridLayout.astro, src/pages/about.astro, src/pages/archive/category/[category].astro, src/pages/archive/tag/[tag].astro, src/pages/posts/[...slug].astro
close: https://github.com/saicaca/fuwari/issues/55
=> feat: add dynamic descript to meta head

src/config.ts, src/layouts/Layout.astro, src/types/config.ts
**Purpose:** Allow user to set their own favicon via settings
**Additional:** I don't want to use recursive conditional types for generating favicons for 64px, 128px, etc... I have no confident not to break anything.
=> feat: allow user to customize favicon

README.ja-JP.md, README.md, README.zh-CN.md
links to the JapaneseWe have added a `README.ja-JP.md` translated into Japanese.
Links to the Japanese description have been added to both `README.md` and `README.zh-CN.md`.
=> Add a description in Japanese.

package.json, pnpm-lock.yaml, src/components/GlobalStyles.astro, src/components/LightDarkSwitch.svelte, src/components/Navbar.astro, src/components/Search.svelte, src/components/widget/DisplaySettings.svelte, src/components/widget/NavMenuPanel.astro, src/i18n/i18nKey.ts, src/i18n/languages/en.ts, src/i18n/languages/ja.ts, src/i18n/languages/zh_CN.ts, src/i18n/languages/zh_TW.ts, src/layouts/Layout.astro, src/utils/setting-utils.ts
=> feat: option to follow the system-wide light/dark mode

src/layouts/Layout.astro
fix issue #63 
set `<html lang="">` to siteConfig language setting
=> fix: set html lang to siteConfig lang

src/components/LightDarkSwitch.svelte, src/types/config.ts, src/utils/setting-utils.ts
https://github.com/saicaca/fuwari/assets/8542907/00a895cb-4f58-45a6-b1b4-453d5d109c2c
https://github.com/saicaca/fuwari/assets/8542907/d6d333f1-79c0-4a65-909f-c6eeec634674
=> feat: light dark mode auto switch

src/components/misc/ImageWrapper.astro, src/config.ts, src/types/config.ts
为banner添加position用于调整img的object-position属性，并在config.ts中添加了对应的说明
=> 为Banner添加position配置

src/components/Search.svelte, src/i18n/i18nKey.ts, src/i18n/languages/en.ts, src/i18n/languages/ja.ts, src/i18n/languages/zh_CN.ts, src/i18n/languages/zh_TW.ts
Added missing "search" localization, text in other languages need to be added
=> feat(i18n): add missing `Search` key

package.json, pnpm-lock.yaml, src/components/comment/Disqus.astro, src/components/comment/Giscus.astro, src/components/comment/Twikoo.astro, src/components/comment/index.astro, src/config.ts, src/pages/posts/[...slug].astro, src/types/config.ts
为 fuwari 添加了评论模块，支持 [Disqus](https://disqus.com/)、[Giscus](https://giscus.app/) 和 [Twikoo](https://twikoo.js.org/) 三种评论服务，都需要前往对应平台获取相应配置项。
Disqus:
Giscus:
Twikoo:
=> ✨ feat: Add comment component and comment configuration

package.json, pnpm-lock.yaml, src/components/ArchivePanel.astro, src/pages/archive/tag/[tag].astro, src/pages/rss.xml.ts, src/plugins/remark-directive-rehype.js, src/types/config.ts, src/utils/content-utils.ts, src/utils/setting-utils.ts, tsconfig.json
1. Add types to data and post.
2. Modify to make type checking pass throughout.
=> Fix to make it type safe.

src/i18n/languages/es.ts, src/i18n/translation.ts
Added Spanish translation for site content and interface elements.
=> Add Spanish Translation

biome.json
docs [here](https://biomejs.dev/reference/configuration/#javascriptformattertrailingcomma)
=> chore(biome): fix deprecated field `trailingComma`

src/components/Footer.astro, src/components/GlobalStyles.astro, src/components/Navbar.astro, src/components/control/BackToTop.astro, src/components/widget/SideBar.astro, src/config.ts, src/layouts/Layout.astro, src/layouts/MainGridLayout.astro, src/types/config.ts
- Reimplement banner height changes in a way that doesn't affect the page layout to minimize lag.
- Fix the jumping caused by different page heights during transitions.
- Redesign the footer.
=> perf: optimizing page transition

src/layouts/Layout.astro, src/layouts/MainGridLayout.astro, src/pages/posts/[...slug].astro
...and "website" for every other page.
=> New prop setOGTypeArticle sets og:type to "article" for posts

astro.config.mjs, pnpm-lock.yaml, src/components/widget/SideBar.astro, src/components/widget/TOC.astro, src/i18n/i18nKey.ts, src/i18n/languages/en.ts, src/i18n/languages/es.ts, src/i18n/languages/ja.ts, src/i18n/languages/ko.ts, src/i18n/languages/zh_CN.ts, src/i18n/languages/zh_TW.ts, src/layouts/MainGridLayout.astro, src/pages/posts/[...slug].astro
=> feat: added TOC

src/base.css
This fixes #189 ,顺带解决在ios浏览器上有点卡卡的问题（）
=> fix: eliminate blue border in iOS browers

package.json, pnpm-lock.yaml, src/layouts/Layout.astro
from this issue
https://github.com/saicaca/fuwari/issues/278
1. add katex dependencies
2. add load katex stylesheet from node_modules
3. remove stylesheet load from a CDN
=> remove load katex stylesheet load from a CDN

scripts/new-post.js
修復了標點符號誤用的問題，變更範圍是終端機的輸出，應該不會影響專案的其他部份
=> fix: output incorrect symbol in console

src/content/posts/markdown.md, src/layouts/Layout.astro
Fix for Long Equations Cut Off (#285)
I fixed the issue where long equations were being cut off in #285. Submitting on behalf of xiyuvi.
=> fix: display issue with long equations

scripts/new-post.js
- Implement recursive directory creation for post folder
- Ensure that parent directories are created if they don't exist
#344
=> feat: add directory creation for post folder

biome.json
This pull request includes significant changes to the `biome.json` configuration file, updating it to a new schema version and refining various settings for file handling, formatting, and linting.
Key changes include:
* Updated the schema version from `1.8.3` to `1.9.4`.
* Added a new `vcs` section to configure version control system settings, including disabling VCS, specifying `git` as the client kind, and not using the ignore file.
* Changed the `indentStyle` from `space` to `tab` and removed other formatting options such as `formatWithErrors`, `indentWidth`, and `lineWidth`.
* Introduced a new `linter` section with enabled status and recommended rules, and added specific rules for overrides in files with extensions like `.svelte`, `.astro`, and `.vue`.
* Modified the `quoteStyle` for …
=> fix(biome): update schema version and refine configuration settings

src/plugins/rehype-component-github-card.mjs
When the fetch function fails or the page is switched, the catch method will be entered, and the catch method will also report an error. This pr modifies the catch method error.
The code was also refactored.
=> fix: Switch page error when fetch fails

src/components/widget/TOC.astro
fix https://github.com/saicaca/fuwari/issues/396
- conditionally render TOC for posts route;
- change warn to debug.
=> fix: TOC warning on home page

src/layouts/MainGridLayout.astro
- The issue is that div element have conflicting display properties in class list. 
- Hidden and flex which both set the display property to different values.
=> fix: conflicting display properties in class list

README.md, docs/README.vi.md, src/config.ts, src/i18n/languages/vi.ts, src/i18n/translation.ts
Add Vietnamese translation and README
=> feat: add Vietnamese translation

src/i18n/languages/tr.ts, src/i18n/translation.ts, src/types/config.ts
=> Turkish translation
