- README.md
- README.zh-CN.md
README中“使用方法”缺少了修改 `site` 字段的步骤，会导致文章尾部 LICENSE 中的链接仍然指向 `fuwari.versel.app`，而非用户自己的博客域名。
> optimized usage instructions

- src/components/widget/Profile.astro
**Proposed change:** 
Verify the target link is presented by the same person: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/me
**Example scenario:** 
Mastodon profile
**Demo**: 
Working as intended:
**Additional:**
As comparison, GitHub profile is doing the same thing:
I can't consider a reason why `nofollow` should be added for blog scenarios, so I only add `me`.
> feat: using rel="me" to verify ownership for websites

- src/components/ConfigCarrier.astro
- src/components/Navbar.astro
- src/config.ts
- src/layouts/Layout.astro
- src/types/config.ts
When deploying a site using Fuwari, visitors can now freely change the theme color. While this is an interesting feature in itself, some site operators might want to fix it to their personal color (at least I did).
At first, I directly edited the layout file to hide it, but how about incorporating it as an option?
> Adding an option to control whether site visitors can change the color theme

- src/layouts/Layout.astro
**Proposed changes:** 
Enhance meta in header for social sharing based on PR (https://github.com/saicaca/fuwari/pull/56). The current version still presents bad in social media like Telegram.
**Before/After:**
Domain -> Site name
I don't think I have time to add "keyword" and "image" in meta list. As suggestion, `og:type=article` should be added when the page type is post. Same for `og:image`, `article:published_time`, `article:tag`, etc. This will make SEO outcome better.  
If I really have free time for this (I want to concentrate on my blog content for now) and not have been merged yet, I will try update some others in the same PR.
> feat: enhanced meta for social sharing (basic)

- package.json
- pnpm-lock.yaml
This snippet solve problem of #23.
Tested in production on:
- Docker
- Windows
- Arch Linux 
- Debian 12
- Ubuntu server 24.04 LTS
> fix: add override to packages of pnpm sharp and vite-imagetools

- src/components/misc/Markdown.astro
- src/i18n/i18nKey.ts
- src/i18n/languages/en.ts
- src/i18n/languages/ja.ts
- src/i18n/languages/zh_CN.ts
- src/i18n/languages/zh_TW.ts
Add a copy button to the top-right corner of a Markdown code block.
> Add Markdown Code Block Copy Functionality.

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/global.d.ts
- src/layouts/Layout.astro
- src/layouts/MainGridLayout.astro
- src/pages/[...page].astro
- src/pages/posts/[...slug].astro
1. Files are formatted by the Astro and Biome VSCode plugins.
2. The modified PhotoSwipeLightbox instance works with all images inside `#post-container`, regardless of image size.
3. Every time a route completes rendering, a new PhotoSwipeLightbox instance is created.
4. Every time before a route change, the old PhotoSwipeLightbox instance is destroyed.
close #131
> feat: add photoswipe for image zoom

- src/pages/posts/[...slug].astro
PhotoSwipe needs to specify the zoom width and height.
1. Display image zoom when remote image metadata is parsed (img element with valid naturalWidth and naturalHeight properties).
2. Show `The image cannot be loaded` on failed image load.
> feat: set the zoom width and height for remote image

- frontmatter.json
- scripts/new-post.js
- src/content/config.ts
- src/layouts/Layout.astro
- src/layouts/MainGridLayout.astro
- src/pages/posts/[...slug].astro
Related issue: #150 
Users can specify the `language` type for individual posts by adding `language: en` (or `zh-CN`, `en-US`, etc. ) to the Markdown frontmatter. This allows for the customization of the `lang` attribute in the `<html>` tag, enhancing accessibility and improving search engine optimization.
Example of the Markdown frontmatter:
```markdown
---
title: Hello World
description: Here goes the description
published: 2024-08-12
draft: false
category: Casual
tags: []
language: en-US
---
```
> feat: add language as post property

- src/components/Navbar.astro
This PR addresses an issue where the responsive menu fails to function correctly on small screens when the **_themeColor.fixed_** option in **_config.ts_** is set to **_true_**. The main cause was a TypeError occurring due to the absence of certain DOM elements when this configuration was active.
- Added conditional checks in the **_loadButtonScript_** function within **_Navbar.astro_** to ensure that elements like **_display-settings-switch_** and **_nav-menu-switch_** are present before attaching event listeners.
- This update prevents the script from attempting to access **_null_** elements, thus resolving the issue that caused the responsive menu to break.
This PR is linked to issue [#159](https://github.com/saicaca/fuwari/issues/159), which describes the problem in detail.
> Fix Responsive Menu and DOM Errors When themeColor.fixed is Set to true

- src/components/Search.svelte
This fixes #181 by adding the CSS suggested.
Search bar selected in Firefox
> fix: remove blue outline on search

- src/components/Footer.astro
**Proposed change:** Use server-side date to dynamically generate copyright year.
**Additional info:**
I considered the client-side date, by appending the following code to the end,
```html
<script>
document.getElementById("copyright-year").innerText = new Date().getFullYear();
</script>
```
Overlooking the potential SEO issue (search engine will not execute the script on client side), it only works on desktop view, not working on mobile view. I cannot tell how to fix it.
> Dynamically generate copyright year 

- .npmrc
- package.json
close #228 #229 
- Use version control after pnpm9.7 by writing `manage-package-manager-versions = true` in .npmrc.
- update pnpm version
- Force use of pnpm.
> Abolish Corepack for packageManager management

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/widget/TOC.astro
- src/styles/variables.styl
Glad to know new toc was released.
As in https://github.com/saicaca/fuwari/pull/103, I'd like to focus solely on adding features rather than the TOC widget itself. 
New features for the existing toc
1. active headings indicator
2. synchronization with page scrolling
I think the implementation needs further discussion, as I'm not fully satisfied with the current solution. 
It seems there will be some updates for the TOC on mobile and its styling, so I haven't tested those cases.
>  New features for TOC

- src/components/control/BackToTop.astro
The back-to-top wrapper element is hidden but blocks hover events from other elements that may overlap in the same position. NOTE that this does not affect any component in the current design. I happened to notice this on a different fork where it was causing an issue and therefore I suggest the change but feel free to ignore this if you think is not relevant enough or could cause problems with the back to top component.
> Removing pointer-events from BackToTop wrapper

- src/components/widget/TOC.astro
fixed bugs in fallback, markVisibleSection, and refined requestAnimationFrame and connectedCallback logic.
> revise TOC logic

- src/components/control/ButtonLink.astro
When the number of posts in a category reaches 4 or even 3 digits the component does not look correct. I have added 2px padding to the ButtonLink badge div to fix this issue. That said, the fact that not all badges have the same width does not convince me but I am not a UX expert so I'll trust your judgement.
With the change it looks like this
Without the change it looks like this
and it can get worse
> added padding to ButtonLink badge div

- src/components/Navbar.astro
This pull request fixes the issue where the search component was missing in production.
- Replaced `client:load` with `client:only="svelte"` when rendering the search component to ensure proper loading in production.
Fixes #253
> fix: search component to client side only for svelte

- package.json
If you run lint on current main you will get at the top:
```
internalError/fs  DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠ The argument --apply is deprecated, it will be removed in the next major release. Use --write instead.
```
> fix: change deprecated --apply flag to --write

- src/components/misc/Markdown.astro
This code will be executed every time you enter the page, which will cause memory leaks.
At the same time, it has been tested that there is no need to execute this code.
> refactor: remove useless code

- src/components/PostCard.astro
- src/components/control/Pagination.astro
- src/components/misc/ImageWrapper.astro
- src/components/widget/TOC.astro
- src/plugins/rehype-component-admonition.mjs
- src/plugins/rehype-component-github-card.mjs
- src/plugins/remark-directive-rehype.js
- src/plugins/remark-excerpt.js
This pull request includes several changes to improve code consistency, correct syntax, and add comments to ignore specific linting rules. The changes affect multiple files across the project.
* [`src/components/control/Pagination.astro`](diffhunk://#diff-8ffe2a069ccb1bd73de30b3e7fd8f5f269b1973704ff1f062802540bb6f833cbL40-R48): Corrected equality checks from `==` to `===` and adjusted code formatting for better readability. [[1]](diffhunk://#diff-8ffe2a069ccb1bd73de30b3e7fd8f5f269b1973704ff1f062802540bb6f833cbL40-R48) [[2]](diffhunk://#diff-8ffe2a069ccb1bd73de30b3e7fd8f5f269b1973704ff1f062802540bb6f833cbL22-R23)
* [`src/components/widget/TOC.astro`](diffhunk://#diff-7f89d17674c4659b071e362b6966e1841d4d15532caed6f3c8bc730c7dc490dcL21-R21): Changed equality check from `!=` to `!==` for …
> fix: biome linter error

- pagefind.yml
In the current Pagefind configuration, mathematical equations are indexed.
As the number of equations increases, excessive Katex syntax appears in search results, which is mostly meaningless.
To reduce build time, I have excluded this syntax from indexing.
> feat: exclude Katex elements from Pagefind indexing

- src/components/Navbar.astro
In navbar component, the LightDarkSwitch svelte component was used with the incorrect directive. This led to a warning in the console when the app is built and previewed. `client:only="svelte"` must be used to fix this warning.
The documentation for this:
https://docs.astro.build/en/reference/directives-reference/#clientonly
> fix: svelte component causing hydration mismatch warning

- src/components/control/Pagination.astro
Modifying the base configuration in the current project will cause the pagination component to be unable to use the previous and next pages. This is because astro carries the base path by default.
https://github.com/withastro/astro/issues/10358
I modified this and tested paths like "", "/", "xxx" and "xxx/xxxx/"
> fix: The previous and next pages carry baseurl

- src/components/PostCard.astro
- src/components/PostPage.astro
This pull request includes changes to the `PostCard` and `PostPage` components to improve type safety by replacing the `any` type with the `CollectionEntry` type from `astro:content`.
Improvements to type safety:
* [`src/components/PostCard.astro`](diffhunk://#diff-4498ff96dd152c425ae39e667ed9f369256259ea9d26bc791d85d0a2e68a6ef4R3): Imported `CollectionEntry` from `astro:content` and updated the `entry` prop type to `CollectionEntry<"posts">`. [[1]](diffhunk://#diff-4498ff96dd152c425ae39e667ed9f369256259ea9d26bc791d85d0a2e68a6ef4R3) [[2]](diffhunk://#diff-4498ff96dd152c425ae39e667ed9f369256259ea9d26bc791d85d0a2e68a6ef4L12-R13)
* [`src/components/PostPage.astro`](diffhunk://#diff-25fd4f9a2e0a43e96904f8eca5f7e5d8f96036ad3d21c623ddf6ca0b3c6064a9R2): Imported `CollectionEntry` from …
> refactor: replace 'any' type with CollectionEntry

- src/components/Search.svelte
Add a maximum height for the current query panel
before:
after:
> style: The search panel exceeds the entire page

- astro.config.mjs
- package.json
- pnpm-lock.yaml
This pull request removes the `astro-compress` integration and its related dependencies from the project configuration and package management files. The changes streamline the configuration and simplify the dependency tree.
* Removed `astro-compress` from the `astro.config.mjs` integrations list, including its configuration options. (`astro.config.mjs`)
* Deleted the `astro-compress` package from `package.json`. (`package.json`)
* Removed `astro-compress` and its transitive dependencies (e.g., `deepmerge-ts`, `html-minifier-terser`, `clean-css`, etc.) from `pnpm-lock.yaml`. This includes both the `packages` and `snapshots` sections. (`pnpm-lock.yaml`) [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL56-L58) …
> 364 remove astro compress2

- src/components/PostMeta.astro
- src/components/widget/Tags.astro
- src/content/posts/reserved-character-test.md
- src/pages/archive/tag/[tag].astro
This pull request introduces changes to improve handling of reserved characters in tags across the application. The updates ensure that tags with special characters are properly encoded and decoded, preventing potential issues with URLs and routing. Additionally, a new test post is added to validate these changes.
* [`src/components/PostMeta.astro`](diffhunk://#diff-e49ad2b45728c5139fcce0c5b309b5c05e54a89977dada8c726fd5fb313df712L73-R73): Updated the `href` attribute for tag links to use `encodeURIComponent` to properly encode special characters in tag URLs.
* [`src/components/widget/Tags.astro`](diffhunk://#diff-717ccf3787b3f8eb930b9b9598e58a96bdbb0b183d95c9eee0ef3d8550de3284L26-R26): Modified the `href` attribute in `ButtonTag` components to use `encodeURIComponent` for consistent …
> fix: Encode URI components for tag links to handle reserved characters

- src/components/PostMeta.astro
- src/components/control/Pagination.astro
- src/components/misc/License.astro
- src/components/misc/Markdown.astro
- src/components/widget/Categories.astro
- src/layouts/MainGridLayout.astro
- src/pages/[...page].astro
This pull request updates the string interpolation syntax in multiple components to use template literals instead of backticks with no interpolation. This change improves code consistency and ensures proper handling of dynamic values.
* `src/components/PostMeta.astro`:
- Updated the `aria-label` attribute in category links to use template literals for dynamic category names.
- Updated the `aria-label` attribute in tag links to use template literals for dynamic tag names.
* `src/components/control/Pagination.astro`:
- Updated the `aria-label` attribute in pagination links to use template literals for dynamic page numbers.
> fix: Correct template literals for aria-label/class/style attributes

- src/components/PostMeta.astro
- src/components/widget/Categories.astro
- src/components/widget/Tags.astro
- src/content/posts/cjk-test.md
- src/pages/archive/category/[category].astro
- src/pages/archive/tag/[tag].astro
- src/utils/content-utils.ts
- src/utils/encoding-utils.ts
- src/utils/url-utils.ts
This pull request introduces several improvements to URL handling, tag/category management, and content encoding across the codebase. The changes aim to ensure consistent trimming, encoding, and decoding of strings, particularly for tags and categories, while also adding support for CJK (Chinese, Japanese, Korean) characters in URLs. Additionally, a new content file has been added for testing edge cases.
* Added `encodePathSegment` and `decodePathSegment` utility functions in `src/utils/encoding-utils.ts` to standardize URL encoding and decoding across the application.
* Updated `getTagUrl` and `getCategoryUrl` in `src/utils/url-utils.ts` to use the new encoding utilities and ensure trimmed input.
* Replaced direct calls to `encodeURIComponent` with `encodePathSegment` in tag and …
> fix: incorrect encoding occurred in CJK.

- src/utils/url-utils.ts
This pull request improves URL handling in the `src/utils/url-utils.ts` file by introducing internationalization support and enhancing the logic for generating category URLs.
* [`src/utils/url-utils.ts`](diffhunk://#diff-5d34aa8ca66f6e6adaf5b1a2550b242706a678e7a48666323d05deda3d8cdee6R1-R3): Added imports for `I18nKey` and `i18n` to enable internationalization functionality.
* [`src/utils/url-utils.ts`](diffhunk://#diff-5d34aa8ca66f6e6adaf5b1a2550b242706a678e7a48666323d05deda3d8cdee6L22-R30): Updated the `getCategoryUrl` function to handle cases where the category is empty, consists only of whitespace, or matches the localized "uncategorized" string. These cases now return the archive URL (`"/archive/"`).
> fix: improve category URL handling with additional checks

- src/components/ArchivePanel.svelte
- src/components/PostCard.astro
- src/pages/posts/[...slug].astro
Noticed many things had the reading and word count thing as "1 minutes", which isn't the proper form. This PR addresses said issues.
> use correct s thingy in english for words & reading time

- docs/README.ko.md
Hello,
I noticed that the `README.ko.md` file was outdated and missing some of the new content from the main `README.md`.
This PR updates the Korean README to match the latest information, with the following key changes:
- Added missing sections: 'Features', 'Commands', and 'License'.
- Corrected the example code in the 'Frontmatter' section.
- Fixed outdated information and awkward translations.
Please review and merge when you have a moment. Thank you!
> docs: update Korean README to match the main README

- src/components/widget/TOC.astro
Fix missing table of content if base url is set, as we currently display it only if url starts with `/posts/` and thats not true in case of set base url, e.g. in gh pages deployment for repository.
Also, its real fix for https://github.com/saicaca/fuwari/issues/475
> fix:  missing toc if base url is set

- src/pages/rss.xml.ts
Fix wrong post url in rss if base url is set. 
Similar problem as in https://github.com/saicaca/fuwari/pull/550
> fix: missing base path in rss

- src/plugins/expressive-code/language-badge.ts
- src/styles/expressive-code.css
Specify JetBrains Mono for code block titles and language badges to unify code block fonts.
Create sample content with one titled code block and one untitled code block.
Before: 
After:
Sometimes the compiled result breaks the code block styles, but I’m not sure what causes it. You can visit <https://xeonzilla.top/posts/twikoo-cloudflare_update/#%E6%9B%B4%E6%96%B0%E4%BE%9D%E8%B5%96> to see how the fonts look when applied.
> fix: define fonts for code block titles and language badges

- .gitignore
- src/components/widget/TOC.astro
N/A
Properly update the activate indicator when no sections are active
Create a long document with no markdown headers towards the top. When the page is scrolled all the way to the top (and no headers are visible on the screen), the active sections overlay in the Table of Contents breaks, and displays as a single line at the very bottom of the ToC.
Here's the broken line in the ToC:
Here's a sample article that will trigger the bug:
```md
---
title: Test
published: 2025-08-07
tags: [Markdown, Blogging, Demo]
category: Examples
draft: true
---
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
f
This article is currently in a draft state and is not published. Therefore, it will not be visible to the general audience. The content is still a work in progress and may require …
```
> fix(TOC): hide active overlay when no sections active

- src/config.ts
---
---
---
Correct language setting reminder, zh-CN -> zh_CN .
---
This change only involves a text comment and does not affect any functionality. No specific testing is required.
---
---
Before this fix, if the user filled in 'zh-CN' in SiteConfig, the deployment result was 'en'.
> fix: Correct language setting reminder, zh-CN -> zh_CN

- src/components/widget/DisplaySettings.svelte
There was no bug for this, but if you display the theme color selector on safari on iOS and the reset to default theme color button is visible, you can see that after the fade in animation finished to show the popup there is an abrupt change of position of this button.
> Fixing Theme Color Selection Reset Button Animation

- src/components/control/ButtonLink.astro
For some reason, there's a hardcoded style for the background when there's already a variable for these values being used in other places.
> Replacing hardcoded style for existing variable in Button Link

- src/styles/variables.styl
I'm not a UI pro, nor do I currently have my main monitor available for proper display, but I'd say this improves the contrast and visibility of the TOC in the light theme, but try on your side and decide.
> Improving contrast TOC light theme
